"""add inventory reservations

Revision ID: 60fad835c509
Revises: c33af833353e
Create Date: 2026-08-04 18:46:42.636773

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "60fad835c509"
down_revision: str | Sequence[str] | None = "c33af833353e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_reservations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("inventory_level_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Text(),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column("external_reference", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'released', 'consumed')",
            name="ck_inventory_reservations_status_valid",
        ),
        sa.CheckConstraint(
            "quantity > 0",
            name="ck_inventory_reservations_quantity_positive",
        ),
        sa.ForeignKeyConstraint(
            ["inventory_level_id"],
            ["inventory_levels.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_reservations_inventory_level_id"),
        "inventory_reservations",
        ["inventory_level_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_reservations_status"),
        "inventory_reservations",
        ["status"],
        unique=False,
    )
    op.add_column(
        "inventory_levels",
        sa.Column(
            "reserved_quantity",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.create_check_constraint(
        "ck_inventory_levels_reserved_quantity_non_negative",
        "inventory_levels",
        "reserved_quantity >= 0",
    )
    op.create_check_constraint(
        "ck_inventory_levels_reserved_quantity_not_above_quantity",
        "inventory_levels",
        "reserved_quantity <= quantity",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_inventory_levels_reserved_quantity_not_above_quantity",
        "inventory_levels",
        type_="check",
    )
    op.drop_constraint(
        "ck_inventory_levels_reserved_quantity_non_negative",
        "inventory_levels",
        type_="check",
    )
    op.drop_column("inventory_levels", "reserved_quantity")
    op.drop_index(
        op.f("ix_inventory_reservations_status"),
        table_name="inventory_reservations",
    )
    op.drop_index(
        op.f("ix_inventory_reservations_inventory_level_id"),
        table_name="inventory_reservations",
    )
    op.drop_table("inventory_reservations")
    # ### end Alembic commands ###
