"""add order fulfillment

Revision ID: 79c30dbaea56
Revises: 91126719034a
Create Date: 2026-08-10 14:23:18.961447

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "79c30dbaea56"
down_revision: str | Sequence[str] | None = "91126719034a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("fulfilled_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_constraint("ck_orders_status_valid", "orders", type_="check")
    op.create_check_constraint(
        "ck_orders_status_valid",
        "orders",
        "status IN ('draft', 'placed', 'cancelled', 'fulfilled')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_orders_status_valid", "orders", type_="check")
    op.create_check_constraint(
        "ck_orders_status_valid",
        "orders",
        "status IN ('draft', 'placed', 'cancelled')",
    )
    op.drop_column("orders", "fulfilled_at")
    # ### end Alembic commands ###
