"""add organization types

Revision ID: b1f66e0530b0
Revises: 60fad835c509
Create Date: 2026-08-05 10:17:43.135364

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b1f66e0530b0"
down_revision: str | Sequence[str] | None = "60fad835c509"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column(
            "organization_type",
            sa.String(length=20),
            server_default=sa.text("'supplier'"),
            nullable=False,
        ),
    )
    op.create_check_constraint(
        "ck_organizations_type_valid",
        "organizations",
        "organization_type IN ('supplier', 'buyer', 'both')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_organizations_type_valid",
        "organizations",
        type_="check",
    )
    op.drop_column("organizations", "organization_type")
    # ### end Alembic commands ###
