"""create inventory tables

Revision ID: c33af833353e
Revises: 87c6e5cb83ef
Create Date: 2026-08-03 17:37:17.123608

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c33af833353e"
down_revision: str | Sequence[str] | None = "87c6e5cb83ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_levels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column(
            "quantity", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity >= 0", name="ck_inventory_levels_quantity_non_negative"
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["warehouse_id"], ["warehouses.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "warehouse_id",
            "product_id",
            name="uq_inventory_levels_warehouse_id_product_id",
        ),
    )
    op.create_index(
        op.f("ix_inventory_levels_product_id"),
        "inventory_levels",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_levels_warehouse_id"),
        "inventory_levels",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "stock_movements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("inventory_level_id", sa.Uuid(), nullable=False),
        sa.Column("quantity_delta", sa.Integer(), nullable=False),
        sa.Column("resulting_quantity", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity_delta <> 0", name="ck_stock_movements_quantity_delta_non_zero"
        ),
        sa.CheckConstraint(
            "resulting_quantity >= 0",
            name="ck_stock_movements_resulting_quantity_non_negative",
        ),
        sa.ForeignKeyConstraint(
            ["inventory_level_id"], ["inventory_levels.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_movements_inventory_level_id"),
        "stock_movements",
        ["inventory_level_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_stock_movements_inventory_level_id"), table_name="stock_movements"
    )
    op.drop_table("stock_movements")
    op.drop_index(
        op.f("ix_inventory_levels_warehouse_id"), table_name="inventory_levels"
    )
    op.drop_index(op.f("ix_inventory_levels_product_id"), table_name="inventory_levels")
    op.drop_table("inventory_levels")
    # ### end Alembic commands ###
