"""add order status history

Revision ID: e90bc3bd9ac7
Revises: 79c30dbaea56
Create Date: 2026-08-10 15:13:54.344335

"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e90bc3bd9ac7"
down_revision: str | Sequence[str] | None = "79c30dbaea56"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_status_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "from_status IS NULL OR "
            "from_status IN ('draft', 'placed', 'cancelled', 'fulfilled')",
            name="ck_order_status_events_from_status_valid",
        ),
        sa.CheckConstraint(
            "to_status IN ('draft', 'placed', 'cancelled', 'fulfilled')",
            name="ck_order_status_events_to_status_valid",
        ),
        sa.CheckConstraint(
            "from_status IS NULL OR from_status <> to_status",
            name="ck_order_status_events_status_changed",
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_status_events_order_id"),
        "order_status_events",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_status_events_to_status"),
        "order_status_events",
        ["to_status"],
        unique=False,
    )

    orders = sa.table(
        "orders",
        sa.column("id", sa.Uuid()),
        sa.column("status", sa.String()),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    status_events = sa.table(
        "order_status_events",
        sa.column("id", sa.Uuid()),
        sa.column("order_id", sa.Uuid()),
        sa.column("from_status", sa.String()),
        sa.column("to_status", sa.String()),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    existing_orders = op.get_bind().execute(
        sa.select(orders.c.id, orders.c.status, orders.c.created_at)
    )
    initial_events = [
        {
            "id": uuid.uuid4(),
            "order_id": row.id,
            "from_status": None,
            "to_status": row.status,
            "created_at": row.created_at,
        }
        for row in existing_orders
    ]
    if initial_events:
        op.bulk_insert(status_events, initial_events)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_order_status_events_to_status"),
        table_name="order_status_events",
    )
    op.drop_index(
        op.f("ix_order_status_events_order_id"),
        table_name="order_status_events",
    )
    op.drop_table("order_status_events")
    # ### end Alembic commands ###
